// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetAllBooks(ctx context.Context) ([]Book, error)
	GetBook(ctx context.Context, id int32) (Book, error)
	GetBooksByCategory(ctx context.Context, category BookCategory) ([]Book, error)
}

var _ Querier = (*Queries)(nil)
